name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    
    - name: Build and test
      run: swift test
