name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Swift
        uses: actions/setup-swift@v2
        with:
          swift-version: '5.5'
          
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    
    - name: Build and test
      run: swift test --platform ios --enable-code-coverage --destination 'platform=iOS Simulator,name=iPhone 12'
